### ISSUE TITLE
protected

### ISSUE THREAD

**Issue by sol-myob** [MarioSinovcic/Game-Of-Life#4]
https://github.com/MarioSinovcic/Game-Of-Life/blob/3cbbc23c0ee8da5a50153443eaed6409e983170b/Game%20Of%20Life/Domain/Grid.cs#L29

you dont have any inheritors of this class, and have provided override for any methods via the virtual keyword.

it makes more sense to use private for the setters, at the moment to inherit this class if only half baked

**Comment by MarioSinovcic** [comment]
👍
